- cico_build_deploy.sh
> Update CI script to push to eclipse repo for upstream k8s image puller

- cico_functions.sh
> add REGISTRY variable in docker login

- cico_functions.sh
> Disable selinux

- cico_functions.sh
> correct docker push command

- cico_functions.sh
> Update version of git in test runner

- cico_functions.sh
> Remove git before upgrading

- deploy/helm/values.yaml
- deploy/openshift/app.yaml
- deploy/openshift/configmap.yaml
- deploy/openshift/serviceaccount.yaml
Use the eclipse kubernetes-image-puller image, convert configmap to template
> Template fixes

- README.md
This is the initial configuration/installation instructions.  Building/testing to come.
> Initial draft of upstream docs

- docker/rhel.Dockerfile
> Change WORKDIR to che-incubator in rhel Dockerfile

- cico_functions.sh
> centos.Dockerfile instead of Dockerfile.centos

- cico_functions.sh
Install latest docker when running CI for multistage buidls
> Install a newer version of docker for multistage builds

- README.md
- cico_functions.sh
Switching ci to the UBI based image. Updating build instructions in README + adding 'nightly' CI icon
> CRW-875 Switching ci to the UBI based image. Updating build instructions in README + adding 'nightly' CI icon

- .github/bin/make-branch.sh
Change-Id:...
pull-before-push
Change-Id: I4ba2a3e4c724104e9bcf19ff7e82f543d73ace86
Signed-off-by: nickboldt <nboldt@redhat.com>
N/A
N/A (or see commit message above for issue number)
N/A
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)
Reviewers, please comment how you tested the PR when approving it.
> pull-before-push

- docker/Dockerfile
Change-Id:...
update base images and rpms
Change-Id: I9a74dc2419247708be55b97695b9283d9f37c9f1
Signed-off-by: nickboldt <nboldt@redhat.com>
N/A
N/A (or see commit message above for issue number)
N/A
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)
Reviewers, please comment how you tested the PR when approving it.
> update base images and rpms

- README.md
- cfg/config.go
- cfg/config_test.go
- cfg/envvars.go
- cfg/envvars_test.go
- deploy/helm/templates/configmap.yaml
- deploy/helm/values.yaml
- deploy/openshift/configmap.yaml
- utils/clusterutils.go
@ibuziuk my preview branch did not seemed to want to merge, so I ended up replaying my changes on a different branch. 
Here is the resulting clean PR. 
Previous PR was : https://github.com/che-incubator/kubernetes-image-puller/pull/41
> Add support for pod Affinity

- README.md
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>
> (docs) Updating Readme.md - removing misleading and obsolete information

- README.md
To match the namespace in line 75.
Signed-off-by: David Kwon <dakwon@redhat.com>
> Change namespace name in README

- hack/run-e2e.sh
chore: use :next instead of :nightly ( eclipse/che/issues/19291 )
Change-Id: Ia1c826f1848bbf2f80c1a86469b6790329b36a0b
Signed-off-by: nickboldt <nboldt@redhat.com>
N/A
N/A (or see commit message above for issue number)
N/A
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)
Reviewers, please comment how you tested the PR when approving it.
> chore: use :next instead of :nightly ( eclipse/che/issues/19291 )

- .github/workflows/next-build.yml
Signed-off-by: Mykhailo Kuznietsov <mkuznets@redhat.com>
https://github.com/eclipse/che/issues/20200
> chore: Update Mattermost GH Action to 1.1.0 version

- .github/workflows/try-pr-on-eclipse-che-hosted-by-red-hat.yaml
- README.md
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>
> Minor README.md fixup

- devfile.yaml
Adding pull request plugin to devfile specification
> feat: Adding pull request plugin to devfile specification

- .github/workflows/make-branch.yaml
- .github/workflows/next-build.yml
- .github/workflows/try-in-web-ide.yaml
Signed-off-by: sdawley <sdawley@redhat.com>
Addresses https://github.com/eclipse/che/issues/21763
> Chore: update ubuntu to 22.04 and actions to use node 16 for #21763

- .github/workflows/next-build.yml
replace deprecated set-output in GH actions
https://github.com/eclipse/che/issues/21993
> chore: che-21993 replace deprecated set-output in actions
